services:
  bot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - OFFERS_DATABASE_ID=${OFFERS_DATABASE_ID}
      - ADVERTISERS_DATABASE_ID=${ADVERTISERS_DATABASE_ID}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped 