services:
  - type: web
    name: telegram-bot-app
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn api.telegram:app --host 0.0.0.0 --port $PORT
    autoscaling:
      min: 1
      max: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    plan: free
    resources:
      cpu: 0.1
      memory: 512